name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 部署分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: nodeServer

      - name: Generate API documentation
        run: npm run doc
        working-directory: nodeServer

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./nodeServer/apidoc
